### ISSUE TITLE
How to use files in dist folder

### ISSUE THREAD

**Issue by deearcodes** [lucascosta/facebook-js-ads-sdk#12]
Hello, 

Thank you for your contribution with this package, it's great!

I'm using Rollup as suggested in the docs but can't wrap my head around how to use de files in the dist folder.

Any guide?

**Comment by lucascosta** [comment]
@deearcodes , you should get acquaintanced to each kind of module system in JS. Here is an article on that: https://auth0.com/blog/javascript-module-systems-showdown/
