### ISSUE TITLE
Update API to v2.8 

### ISSUE THREAD

**Issue by dearcodes** [lucascosta/facebook-js-ads-sdk#13]
Are there any plans to update API to 2.8? 

[Changes](https://developers.facebook.com/docs/apps/changelog) don't seem difficult to integrate.

**Comment by lucascosta** [comment]
Wanna help?

**Comment by deearcodes** [comment]
Sure, I'll get on it

**Comment by Stefflan00** [comment]
@deearcodes @lucascosta  Whats the status on that? would love to help on that as well.

**Comment by lucascosta** [comment]
@Stefflan00 I'm not being able to get work on this as of now, although it would probably not be hard, since weren't many changes. Since we still have until April, the current code should be fine for most cases. If you guys want to PR this I'll try to check it ASAP.

**Comment by Stefflan00** [comment]
@lucascosta this is what i thought as well but just ran in an error by pulling all my adAccounts of my user: 
```
{"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.","type":"OAuthException","code":2635,"fbtrace_id":"EGFpBOvhQda"}}%  
```

changing the url from 2.7 => 2.8 gives me back the response i expected. So I will have a look.

**Comment by deearcodes** [comment]
I'm working on it will do a pull request Today.

**Comment by jonahlau** [comment]
hi guys, any updates on the upgrade to 2.8?

**Comment by uargh** [comment]
Any news on this? Facebook is deprecating all versions below 2.8 starting March 27th.

**Comment by lucascosta** [comment]
https://github.com/lucascosta/facebook-js-ads-sdk/releases
