### ISSUE TITLE
getCampaign throwing a Facebook error.

### ISSUE THREAD

**Issue by wyattbenno777** [lucascosta/facebook-js-ads-sdk#16]
Hello.

I am using https://developers.facebook.com/tools/explorer/ from Facebook to get a token and set temporary permissions. All of the functions work as is other than "account.getCampaigns". When I run this I get an error:

"Tried accessing nonexisting field (campaigns) on node type (User)"

Did they make a change to the API? Is this working for you?

Thank you!

**Comment by lucascosta** [comment]
@wyattbenno777 `account.getCampaigns` is present on the integration tests and it's working fine here. You might wanna check the fields you are requesting.
