### ISSUE TITLE
exportData only returns changes

### ISSUE THREAD

**Issue by talha-asad** [lucascosta/facebook-js-ads-sdk#26]
exportData after saving/updating objects only returns changes, the name of the function should be changed to `exportChanges` or `exportChangesData`, while `exportData` should return all info it has about the object. The data is available in the object but it has other keys which are internal to this lib.

Currently there is no way to gracefully or in a future-proof way get all data for an object.

What are your thoughts on this?

**Comment by lucascosta** [comment]
We should probably implement `exportAllData`, like the Python SDK...
