### ISSUE TITLE
Support for 2.9 version of the API

### ISSUE THREAD

**Issue by talha-asad** [lucascosta/facebook-js-ads-sdk#29]
A newer version of the API is available and needs to be supported. I was thinking we could perhaps land all the improvements and changes in the upcoming week. Thoughts?

**Comment by lucascosta** [comment]
Let me see how my weekend goes...

**Comment by deiks** [comment]
I suggest if you can make option that you define version you want to use if there's someone that needs to use older one for some reason.

**Comment by lucascosta** [comment]
@deiks thank you for your suggestion. I'll leave a branch for older versions from now on.

**Comment by lucascosta** [comment]
@deiks tags can also be used as reference in package.json, so just reference the older release tag if you want: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
