### ISSUE TITLE
NPM and Github version mismatch

### ISSUE THREAD

**Issue by talha-asad** [lucascosta/facebook-js-ads-sdk#3]
Github has version 2.6.1
Would also like to know if this version has anything to do with Facebook API version? If yes, lets upgrade it for 2.7?

**Comment by lucascosta** [comment]
Hi @talha-asad, indeed the version of this repo is meant to be in accordance to the API version. Definitely, let's upgrade it! I think there were a few changes in fields that might have an impact, I'll check that as soon as I can. It would be great if you'd like to contribute too! Thanks

**Comment by talha-asad** [comment]
Thanks for the quick response. I took a small dive in your code, and it seems to be structured well, i'll help you get this upgraded to 2.7.

**Comment by talha-asad** [comment]
Can you match the repo version to 2.6.2 as is published on NPM. So i can do a fork and submit a PR for 2.7.

**Comment by lucascosta** [comment]
Done! Thank you!

**Comment by talha-asad** [comment]
#4 submitted
