### ISSUE TITLE
Facebook Advideos Support ?

### ISSUE THREAD

**Issue by KHANHNQ1** [lucascosta/facebook-js-ads-sdk#30]
The SDK does not support facebook advideos ?

**Comment by lucascosta** [comment]
No, not yet. I'll try to put it in the next versions. PR considered as well.

**Comment by lucascosta** [comment]
Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
