### ISSUE TITLE
User facing api token

### ISSUE THREAD

**Issue by crystalneth** [lucascosta/facebook-js-ads-sdk#34]
For a user facing web app, we don't want to reveal a long-lived API token. I believe the Python API provides a way to obtain a short lived token for this purpose. Is there any plan to add this to the js API? Does anyone have a way they work around this other than layering a server API over this library? For now that's what I plan to do.

Thanks!

**Comment by lucascosta** [comment]
I believe the most secure way is indeed through a server request. I'm open to PRs in this sense. BRs
