### ISSUE TITLE
Support get all adaccounts from User?

### ISSUE THREAD

**Issue by hungchai** [lucascosta/facebook-js-ads-sdk#36]
Does the sdk provide object to get me/adaccounts?

`https://graph.facebook.com/v2.9/me/adaccounts`

**Comment by lucascosta** [comment]
Yes, you can use the `User` class and set the id to `'me'`. There's a `getAdAccounts` method.

https://github.com/lucascosta/facebook-js-ads-sdk/blob/master/src/objects/user.js

**Comment by hungchai** [comment]
Thanks for your quick response !!!!
