### ISSUE TITLE
Support batching

### ISSUE THREAD

**Issue by marcospgp** [lucascosta/facebook-js-ads-sdk#43]
https://developers.facebook.com/docs/graph-api/making-multiple-requests

**Comment by lucascosta** [comment]
Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
