### ISSUE TITLE
Support for v2.10

### ISSUE THREAD

**Issue by fahadAziz44** [lucascosta/facebook-js-ads-sdk#44]
Can you add the support for marketing API v2.10 ?
Thanks in advance.

**Comment by drj-io** [comment]
+1

**Comment by warling** [comment]
+1

Also, I'm looking for a little help getting started with this package. I'm new to the Marketing API and FB development in general, and I've sort of managed to get things working with my sandbox account in PHP and the Graph API Explorer, but cannot get analogous code working with this package even after I forced a change to v2.10. Our whole workflow is based around Node, and I'd really love to get this package integrated into our system, but I've struggled many hours with this trying to get it working without success. If someone could give me a hand and answer some questions, I'd really, REALLY appreciated it! If you'd be willing to answer a few questions, please contact me at darin@bigravenmedia.com. Thanks!

**Comment by warling** [comment]
Is there a good forum for users of this package to discuss problems when they arise? Or is this it?

**Comment by lucascosta** [comment]
https://github.com/lucascosta/facebook-js-ads-sdk/releases/tag/v2.10.1
