### ISSUE TITLE
src/objects/user.js Missing `getEndpoint()` function

### ISSUE THREAD

**Issue by warling** [lucascosta/facebook-js-ads-sdk#46]
The User object class is missing its `getEndpoint()` function:

```
static getEndpoint () {
    return 'users'
  }
```

I'm not sure if this is normally needed, but it seems to be necessary when calling `AdAccount.getUsers` — I get a `TypeError: targetClass.getEndpoint is not a function` error message.

**Comment by lucascosta** [comment]
@warling thanks for the warning. The other SDKS reference `AdAccountUser`, which are different from the `User`. I'll fix it in the next version.

**Comment by warling** [comment]
Awesome. Thanks!

**Comment by lucascosta** [comment]
https://github.com/lucascosta/facebook-js-ads-sdk/releases/tag/v2.10.1
