### ISSUE TITLE
Insights.Fields.age Isn't a Valid Field

### ISSUE THREAD

**Issue by warling** [lucascosta/facebook-js-ads-sdk#47]
It may have been a valid field in an earlier version of the API, but it's not valid as of v2.10:

`message: '(#100) age is not valid for fields param. please check https://developers.facebook.com/docs/marketing-api/reference/ads-insights/ for all valid values'`

**Comment by warling** [comment]
Same applies to `gender`.

**Comment by lucascosta** [comment]
@warling I haven't yet had the time to properly update to 2.10, as I mean to make some improvements. These will fix by then.
