### ISSUE TITLE
adCreative create Error: 'Invalid parameter' code: 1487390

### ISSUE THREAD

**Issue by gi4c0** [lucascosta/facebook-js-ads-sdk#48]
Cannot create adCreative. Get an error: "Adcreative Create Failed: The Adcreative Create Failed for the following reason: Oops, something went wrong. Please try again later" and in the same error stack: 
message: 'Invalid parameter'
code: 1487390
My code:
```exports.create = (data, campaign) => {
  return new adsSdk.AdCreative({
    body: data.appearance.vacancyDescription,
    image_url: data.appearance.backgroundImage,
    name: `Creative for campaign ${campaign.id}`,
    link_url: data.appearance.link,
    title: data.appearance.linkDescription,
    object_story_spec: {
      instagram_actor_id: 'xxxxxx',
      page_id: 'xxxxx',
      link_data: {
        link: data.appearance.link
      }
    }
  }, `act_xxxxx`)
    .create()
```

**Comment by lucascosta** [comment]
Hi @gi4c0 , this error seems transient. Also, it doesn't seem like an error in the SDK, did you try it on other languages?
