### ISSUE TITLE
Insights.DatePresets Enums Invalid as of v2.10

### ISSUE THREAD

**Issue by warling** [lucascosta/facebook-js-ads-sdk#49]
According to https://developers.facebook.com/docs/marketing-api/insights/parameters, the list of allowable enums for `date_preset` has changed as of v2.10. (Look for "Available new date_presets" on the linked page.) I confirmed this by attempting to use some of the old preset names (such as `last_30_days`, which failed) and then trying again using the new preset names (`last_30d`, which succeeded).

**Comment by warling** [comment]
(I would imagine this applies to the `DatePreset` enums in _all_ classes, but I haven't actually looked yet.)

**Comment by lucascosta** [comment]
https://github.com/lucascosta/facebook-js-ads-sdk/releases/tag/v2.10.1
