### ISSUE TITLE
New release for 2.10 has issues with Fields

### ISSUE THREAD

**Issue by avifried1** [lucascosta/facebook-js-ads-sdk#53]
Some objects had the property of `Fields` changed to `Field`, while in the constructor for `AbstractObject` you're still checking for `this.constructor.Fields`:
e.g. in adaccount.js: `static get Field () { ...`
while in core.js: 
`if (this.constructor.Fields === undefined) {
      throw new Error('A "Fields" frozen object must be defined in the object class')
    }`

**Comment by lucascosta** [comment]
I'm waiting if @warling will ammend this commit https://github.com/lucascosta/facebook-js-ads-sdk/pull/52

**Comment by lucascosta** [comment]
fixed by https://github.com/lucascosta/facebook-js-ads-sdk/pull/52
