### ISSUE TITLE
Support post request

### ISSUE THREAD

**Issue by dalmatele** [lucascosta/facebook-js-ads-sdk#56]
Sometime we need to post comment, with PHP facebook SDK we can do by this:
```
$fb_connection_2 = new FacebookConnection($app_id, $app_secret, "v2.9");
$fb_connection_2->connect($fb_token);
$resutl = $fb_connection->sendPostRequest($request, $params);
```

How can I do that in NodeJS version?

**Comment by lucascosta** [comment]
Hi @dalmatele sorry, for the delay. Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
