### ISSUE TITLE
how to add user to custom audience?

### ISSUE THREAD

**Issue by gintonic** [lucascosta/facebook-js-ads-sdk#57]
this sdk can use custom audience to add user to list? if yes, how to do?

this code in java sdk
`User user = new CustomAudience(<CUSTOM_AUDIENCE_ID>, context).createUser()
  .setPayload("{\"schema\":\"EMAIL_SHA256\",\"data\":[\"9b431636bd164765d63c573c346708846af4f68fe3701a77a3bdd7e7e5166254\",\"8cc62c145cd0c6dc444168eaeb1b61b351f9b1809a579cc9b4c9e9d7213a39ee\",\"4eaf70b1f7a797962b9d2a533f122c8039012b31e0a52b34a426729319cb792a\"]}")
  .execute();`

**Comment by K-Ho** [comment]
^ wondering the same thing.

**Comment by danielcolgan** [comment]
+++

**Comment by danielcolgan** [comment]
@gintonic @K-Ho  if you'll find answer please ping me. Thanks!

**Comment by lucascosta** [comment]
Hi, sorry for the delay. Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
