### ISSUE TITLE
adding appsecret_proof parameter?

### ISSUE THREAD

**Issue by K-Ho** [lucascosta/facebook-js-ads-sdk#58]
Currently, API objects are instantiated with an accessToken.  Is there any way to add in the appsecret_proof as a parameter upon instantiation?

https://developers.facebook.com/docs/graph-api/securing-requests/

**Comment by lucascosta** [comment]
Hi @dalmatele, sorry for the delay. Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
