### ISSUE TITLE
A "Field" frozen object must be defined in the object class

### ISSUE THREAD

**Issue by nemo** [lucascosta/facebook-js-ads-sdk#59]
Hey there,

I'm trying to get a list of pages managed by a Business Manager account ([API docs](https://developers.facebook.com/docs/marketing-api/businessmanager/assets)) and running into an issue.

1. Is that `getOwnedPages` pages is hitting `owned_pages` endpoint, which I believe is deprecated (they're all `/pages` now and you pass in an access_type parameter for owned vs. client/agency)

2. Is that `getOwnedPages` doesn't even send the request since `AbstractCrudObject` requires a `Field` attribute to be set, but the `Business` class is passing `AbstractCrudObject` as the object that resolves the endpoint and it's breaking.

Is there a way to get around this? Or do I have to edit the SDK and create a `Page` class for this?

**Comment by nemo** [comment]
Hey @lucascosta – just submitted a PR for this: #60.

Not sure if this is the correct way to do this, but this approach has made it work for us internally. We're using our own version until this is fixed or merged in but would definitely love to see it merged in (or fixed on your end) earlier than later :P

**Comment by lucascosta** [comment]
Hi @nemo sorry, for the delay. Thanks for you contribution but Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
