### ISSUE TITLE
Why have we switched from "Fields" to "Field"?

### ISSUE THREAD

**Issue by marcospgp** [lucascosta/facebook-js-ads-sdk#61]
The official SDK uses "Fields": https://github.com/facebook/facebook-nodejs-ads-sdk

After this commit, "Fields" no longer works and one must use "Field": https://github.com/lucascosta/facebook-js-ads-sdk/commit/22614c0edb91f858872a20de8b115a868085a918

**Comment by lucascosta** [comment]
Hi @marcospgp , sorry for the delay. Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
