### ISSUE TITLE
problem in importing the sdk

### ISSUE THREAD

**Issue by johirbuet** [lucascosta/facebook-js-ads-sdk#9]
I am importing the module using the following command
`import FacebookAdsApi from './../../../node_modules/facebook-ads-sdk/src/api';`
Then once i go to the browser i get the following errors.
I cant event do the import
`import { AdAccount, Campaign } from './../../../node_modules/facebook-ads-sdk/src/objects'`.
It shows the error

> Module not found: Error: Cannot resolve directory './../../../node_modules/facebook-ads-sdk/src/objects'

My other modules are working fine. So i don't have environment issues i believe.

![screen shot 2016-10-20 at 11 19 24 pm](https://cloud.githubusercontent.com/assets/4279025/19586571/e4800ab4-971b-11e6-8f42-731770d7507e.png)
![screen shot 2016-10-20 at 11 19 37 pm](https://cloud.githubusercontent.com/assets/4279025/19586573/e75b75ac-971b-11e6-9b4b-01a8745a93a2.png)

**Comment by johirbuet** [comment]
And this problem also appears when i try to load others like Campaign, AddAccount
using the commands
`import Campaign from './../../../node_modules/facebook-ads-sdk/src/objects/campaign'`
`import AdAccount from './../../../node_modules/facebook-ads-sdk/src/objects/ad-account'`
etc

**Comment by lucascosta** [comment]
@johirbuet `import` is not implemented in any browsers natively at this time. It is implemented in many transpilers, such as the Traceur Compiler, Babel or Rollup. If you want to import the modules as in the examples you must implement a transpiler in your project. 

Also, there is a `dist` folder in this repository in which the code is already transpiled in different module systems, if you want to load it directly in the browser.

**Comment by johirbuet** [comment]
hello i am using babel in my project..

**Comment by johirbuet** [comment]
still why does it show errers?
